# -*- coding: utf-8 -*-
"""H1N1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrDc3q0VjtF9xo9411vP1Ne20Mi8FQJ0

# **H1N1 VACCINE DATASET**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df=pd.read_csv("/h1n1_vaccine_prediction.csv")

df.shape

df.sample(10)

df.dtypes

df.columns

df.info()

df.isnull().sum()

df.head()

df.describe()

iqr=20029-6676
iqr

6676-(1.5*13353)

20029+(1.5*13353)

corr=df.corr()
corr

sns.heatmap(corr,annot=True,cmap="YlGnBu")

sns.countplot(x="h1n1_vaccine",data=df)

df['h1n1_vaccine'].value_counts()

sns.boxplot(x="h1n1_vaccine",data=df)
plt.show()

sns.boxplot(x="chronic_medic_condition",y="h1n1_vaccine",data=df)
plt.title("chronic_medic_condition Vs h1n1_vaccine ")
plt.show()

sns.violinplot(x="chronic_medic_condition",y="h1n1_vaccine",data=df)
plt.title("chronic_medic_condition Vs h1n1_vaccine ")
plt.show()

sns.stripplot(x="chronic_medic_condition",y="h1n1_vaccine",data=df)
plt.title("chronic_medic_condition Vs h1n1_vaccine ")
plt.show()

sns.jointplot(x="chronic_medic_condition",y="h1n1_vaccine",data=df,color="orchid")
plt.title("h1n1_vaccine Vs chronic_medic_condition")
plt.show()

median1=df["h1n1_vaccine"].median()
median1

df=df.dropna()

df.shape

def remove_outlier(col):
    sorted(col)
    q1,q3=col.quantile([0.25,0.75])
    iqr=q3-q1
    lower_range=q1-1.5*iqr
    upper_range=q3+1.5*iqr
    return lower_range,upper_range

"""#**Logistic REGRESSION**"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows',None)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df3=pd.read_csv("/h1n1_vaccine_prediction.csv")

df3.head()

df3.sample(10)

df3.shape

df3.dtypes

df3.info()

df3.isnull().sum()

sns.countplot(x="h1n1_vaccine",data=df3,palette="coolwarm")

df3["h1n1_vaccine"].value_counts()

sns.countplot(x="h1n1_worry",hue="h1n1_vaccine",data=df3)

pd.crosstab(df3["has_health_insur"],df3["h1n1_vaccine"])

df3.head()

df3=df3.dropna()

df3.shape

df3=pd.get_dummies(columns=["qualification","race","sex","income_level","marital_status","housing_status","census_msa","age_bracket"],data=df3)

df3.head()

df3=pd.get_dummies(columns=["employment"],data=df3)

X=df3.drop("h1n1_vaccine",axis=1)
Y=df3["h1n1_vaccine"]

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.30,random_state=1)

model_1=LogisticRegression()

model_1.fit(X_train,Y_train)

model_1.score(X_train,Y_train)

model_1.score(X_test,Y_test)

predictions=model_1.predict(X_test)
predictions

from sklearn import metrics
from sklearn.metrics import accuracy_score

accuracy_score(Y_test,predictions)

cm=metrics.confusion_matrix(Y_test,predictions,labels=[1,0])
df3_cm=pd.DataFrame(cm,index=[i for i in["1","0"]],
 columns=[i for i in ["Predict 1","Predict 0"]])
plt.figure(figsize=(7,5))
sns.heatmap(df3_cm,annot=True,fmt='g')

"""# **DECISIONTREECLASSIFIER**"""

from sklearn.tree import DecisionTreeClassifier

model_6=DecisionTreeClassifier()

model_6.fit(X_train,Y_train)

model_6.score(X_train,Y_train)

model_6.score(X_test,Y_test)

predictions=model_6.predict(X_test)
predictions

from sklearn import metrics
from sklearn.metrics import accuracy_score

accuracy_score(Y_test,predictions)

cm=metrics.confusion_matrix(Y_test,predictions,labels=[1,0])
df3_cm=pd.DataFrame(cm,index=[i for i in["1","0"]],
 columns=[i for i in ["Predict 1","Predict 0"]])
plt.figure(figsize=(7,5))
sns.heatmap(df3_cm,annot=True,fmt='g')

"""# **BAGGING CLASSIFIER**"""

from sklearn.ensemble import BaggingClassifier

model_7= BaggingClassifier(base_estimator=BaggingClassifier(), n_estimators=10, random_state=42)

model_7.fit(X_train,Y_train)

model_7.score(X_train,Y_train)

model_7.score(X_test,Y_test)

predictions=model_7.predict(X_test)
predictions

accuracy_score(Y_test,predictions)

cm=metrics.confusion_matrix(Y_test,predictions,labels=[1,0])
df3_cm=pd.DataFrame(cm,index=[i for i in["1","0"]],
 columns=[i for i in ["Predict 1","Predict 0"]])
plt.figure(figsize=(7,5))
sns.heatmap(df3_cm,annot=True,fmt='g')

